using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NLUC.Units
{
    internal enum Units
    {
        Second,
        Millisecond,
        Minute,
        Metre,
        Kilogram,
        Ampere,
        Kelvin,
        Mole,
        Candela,
        Hours,
        Centimetre,
        Day,
        Week,
        Year,
        Kilometre,
        Mile,
        Feet,
        Inch,
        Decade,
        Century,
        Lumen,
        Hand,
        Gram,
        Celcius,
        Fahrenheit,
        PoundSterling,
        Penny,
        Bit,
        Byte,
        Octect,
        Nibble,
        Kilobit,
        Megabit,
        Gigabit,
        Kilobyte,
        Megabyte,
        Gigabyte,
        Terabit,
        Petabyte,
        Petabit,
        USD,
        Cent,
        Dime,
        Beat,
        Slug,
        Generic,
        Yard,
        Ell,
        Millimetres,
        Digit,
        Palm,
        Fathom,
        Rod,
        League,
        NauticalMile,
        Chain,
        Furlong,
        Link,
        Grain,
        Pennyweight,
        Carat,
        Milligram,
        Atom,
        Moment,
        Scrupulum,
        Microsecond,
        TimeUnit,
        Fortnight,
        Quarantine,
        GalacticYear,
        Millenium,
        Jubilee,
        Semester,
        Barleycorn,
        Line,
        Ton
    }
}
